// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *BulkAllUpdateUsersRequest) setDefaults() {
	{
		val := BulkAllUpdateUsersRequestStatus("ACTIVE")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BulkDeleteUsersByStatusRequest) setDefaults() {
	{
		val := BulkDeleteUsersByStatusRequestStatus("ACTIVE")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BulkUpdateUsersRequestFields) setDefaults() {
	{
		val := BulkUpdateUsersRequestFieldsStatus("ACTIVE")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateHostRequest) setDefaults() {
	{
		val := bool(false)
		s.IsDisabled.SetTo(val)
	}
	{
		val := CreateHostRequestSecurityLayer("DEFAULT")
		s.SecurityLayer.SetTo(val)
	}
	{
		val := bool(false)
		s.IsHidden.SetTo(val)
	}
	{
		val := bool(false)
		s.OverrideSniFromAddress.SetTo(val)
	}
	{
		val := bool(false)
		s.KeepSniBlank.SetTo(val)
	}
	{
		val := bool(false)
		s.ShuffleHost.SetTo(val)
	}
	{
		val := bool(false)
		s.MihomoX25519.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateNodeRequest) setDefaults() {
	{
		val := bool(false)
		s.IsTrafficTrackingActive.SetTo(val)
	}
	{
		val := string("XX")
		s.CountryCode.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateUserRequest) setDefaults() {
	{
		val := CreateUserRequestStatus("ACTIVE")
		s.Status.SetTo(val)
	}
	{
		val := CreateUserRequestTrafficLimitStrategy("NO_RESET")
		s.TrafficLimitStrategy.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *HostItem) setDefaults() {
	{
		val := HostItemSecurityLayer("DEFAULT")
		s.SecurityLayer.SetTo(val)
	}
	{
		val := bool(false)
		s.IsHidden.SetTo(val)
	}
	{
		val := bool(false)
		s.OverrideSniFromAddress.SetTo(val)
	}
	{
		val := bool(false)
		s.KeepSniBlank.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RevokeUserSubscriptionBody) setDefaults() {
	{
		val := bool(false)
		s.RevokeOnlyPasswords.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UpdateHostRequest) setDefaults() {
	{
		val := bool(false)
		s.IsDisabled.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UpdateManyHostsRequest) setDefaults() {
	{
		val := bool(false)
		s.IsDisabled.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UpdateUserRequest) setDefaults() {
	{
		val := UpdateUserRequestTrafficLimitStrategy("NO_RESET")
		s.TrafficLimitStrategy.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UserItemInfo) setDefaults() {
	{
		val := UserItemInfoStatus("ACTIVE")
		s.Status.SetTo(val)
	}
	{
		val := float64(0)
		s.TrafficLimitBytes.SetTo(val)
	}
	{
		val := UserItemInfoTrafficLimitStrategy("NO_RESET")
		s.TrafficLimitStrategy.SetTo(val)
	}
	{
		val := int(0)
		s.LastTriggeredThreshold.SetTo(val)
	}
}
