// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *CreateHostBody) setDefaults() {
	{
		val := bool(false)
		s.IsDisabled.SetTo(val)
	}
	{
		val := CreateHostBodySecurityLayer("DEFAULT")
		s.SecurityLayer.SetTo(val)
	}
	{
		val := bool(false)
		s.IsHidden.SetTo(val)
	}
	{
		val := bool(false)
		s.OverrideSniFromAddress.SetTo(val)
	}
	{
		val := bool(false)
		s.KeepSniBlank.SetTo(val)
	}
	{
		val := bool(false)
		s.ShuffleHost.SetTo(val)
	}
	{
		val := bool(false)
		s.MihomoX25519.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateNodeBody) setDefaults() {
	{
		val := bool(false)
		s.IsTrafficTrackingActive.SetTo(val)
	}
	{
		val := string("XX")
		s.CountryCode.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateUserBody) setDefaults() {
	{
		val := CreateUserBodyStatus("ACTIVE")
		s.Status.SetTo(val)
	}
	{
		val := CreateUserBodyTrafficLimitStrategy("NO_RESET")
		s.TrafficLimitStrategy.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *HostItem) setDefaults() {
	{
		val := HostItemSecurityLayer("DEFAULT")
		s.SecurityLayer.SetTo(val)
	}
	{
		val := bool(false)
		s.IsHidden.SetTo(val)
	}
	{
		val := bool(false)
		s.OverrideSniFromAddress.SetTo(val)
	}
	{
		val := bool(false)
		s.KeepSniBlank.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RevokeUserSubscriptionBody) setDefaults() {
	{
		val := bool(false)
		s.RevokeOnlyPasswords.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UpdateHostBody) setDefaults() {
	{
		val := bool(false)
		s.IsDisabled.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UpdateManyHostsBody) setDefaults() {
	{
		val := bool(false)
		s.IsDisabled.SetTo(val)
	}
}
