// Code generated by ogen, DO NOT EDIT.
package api

type ApiTokensCreateRes interface {
	apiTokensCreateRes()
}

type ApiTokensDeleteRes interface {
	apiTokensDeleteRes()
}

type ApiTokensFindAllRes interface {
	apiTokensFindAllRes()
}

type ApiTokensGetScopesRes interface {
	apiTokensGetScopesRes()
}

type AuthGetStatusRes interface {
	authGetStatusRes()
}

type AuthLoginRes interface {
	authLoginRes()
}

type AuthOauth2AuthorizeRes interface {
	authOauth2AuthorizeRes()
}

type AuthOauth2CallbackRes interface {
	authOauth2CallbackRes()
}

type AuthPasskeyAuthenticationOptionsRes interface {
	authPasskeyAuthenticationOptionsRes()
}

type AuthPasskeyAuthenticationVerifyRes interface {
	authPasskeyAuthenticationVerifyRes()
}

type AuthRegisterRes interface {
	authRegisterRes()
}

type BandwidthStatsNodesGetNodeUserUsageRes interface {
	bandwidthStatsNodesGetNodeUserUsageRes()
}

type BandwidthStatsNodesGetStatsNodeUsersUsageRes interface {
	bandwidthStatsNodesGetStatsNodeUsersUsageRes()
}

type BandwidthStatsNodesGetStatsNodesUsersUsageRes interface {
	bandwidthStatsNodesGetStatsNodesUsersUsageRes()
}

type BandwidthStatsUsersGetStatsNodesUsageRes interface {
	bandwidthStatsUsersGetStatsNodesUsageRes()
}

type BandwidthStatsUsersGetUserUsageByRangeRes interface {
	bandwidthStatsUsersGetUserUsageByRangeRes()
}

type ConfigProfileCreateConfigProfileRes interface {
	configProfileCreateConfigProfileRes()
}

type ConfigProfileDeleteConfigProfileByUuidRes interface {
	configProfileDeleteConfigProfileByUuidRes()
}

type ConfigProfileGetAllInboundsRes interface {
	configProfileGetAllInboundsRes()
}

type ConfigProfileGetComputedConfigProfileByUuidRes interface {
	configProfileGetComputedConfigProfileByUuidRes()
}

type ConfigProfileGetConfigProfileByUuidRes interface {
	configProfileGetConfigProfileByUuidRes()
}

type ConfigProfileGetConfigProfilesRes interface {
	configProfileGetConfigProfilesRes()
}

type ConfigProfileGetInboundsByProfileUuidRes interface {
	configProfileGetInboundsByProfileUuidRes()
}

type ConfigProfileReorderConfigProfilesRes interface {
	configProfileReorderConfigProfilesRes()
}

type ConfigProfileUpdateConfigProfileRes interface {
	configProfileUpdateConfigProfileRes()
}

type ExternalSquadAddUsersToExternalSquadRes interface {
	externalSquadAddUsersToExternalSquadRes()
}

type ExternalSquadCreateExternalSquadRes interface {
	externalSquadCreateExternalSquadRes()
}

type ExternalSquadDeleteExternalSquadRes interface {
	externalSquadDeleteExternalSquadRes()
}

type ExternalSquadGetExternalSquadByUuidRes interface {
	externalSquadGetExternalSquadByUuidRes()
}

type ExternalSquadGetExternalSquadsRes interface {
	externalSquadGetExternalSquadsRes()
}

type ExternalSquadRemoveUsersFromExternalSquadRes interface {
	externalSquadRemoveUsersFromExternalSquadRes()
}

type ExternalSquadReorderExternalSquadsRes interface {
	externalSquadReorderExternalSquadsRes()
}

type ExternalSquadUpdateExternalSquadRes interface {
	externalSquadUpdateExternalSquadRes()
}

type HostsBulkActionsDeleteHostsRes interface {
	hostsBulkActionsDeleteHostsRes()
}

type HostsBulkActionsDisableHostsRes interface {
	hostsBulkActionsDisableHostsRes()
}

type HostsBulkActionsEnableHostsRes interface {
	hostsBulkActionsEnableHostsRes()
}

type HostsBulkActionsSetPortToHostsRes interface {
	hostsBulkActionsSetPortToHostsRes()
}

type HostsCreateHostRes interface {
	hostsCreateHostRes()
}

type HostsDeleteHostRes interface {
	hostsDeleteHostRes()
}

type HostsGetAllHostTagsRes interface {
	hostsGetAllHostTagsRes()
}

type HostsGetAllHostsRes interface {
	hostsGetAllHostsRes()
}

type HostsGetOneHostRes interface {
	hostsGetOneHostRes()
}

type HostsReorderHostsRes interface {
	hostsReorderHostsRes()
}

type HostsUpdateHostRes interface {
	hostsUpdateHostRes()
}

type HwidUserDevicesCreateUserHwidDeviceRes interface {
	hwidUserDevicesCreateUserHwidDeviceRes()
}

type HwidUserDevicesDeleteAllUserHwidDevicesRes interface {
	hwidUserDevicesDeleteAllUserHwidDevicesRes()
}

type HwidUserDevicesDeleteUserHwidDeviceRes interface {
	hwidUserDevicesDeleteUserHwidDeviceRes()
}

type HwidUserDevicesGetAllUsersRes interface {
	hwidUserDevicesGetAllUsersRes()
}

type HwidUserDevicesGetHwidDevicesStatsRes interface {
	hwidUserDevicesGetHwidDevicesStatsRes()
}

type HwidUserDevicesGetTopUsersByHwidDevicesRes interface {
	hwidUserDevicesGetTopUsersByHwidDevicesRes()
}

type HwidUserDevicesGetUserHwidDevicesRes interface {
	hwidUserDevicesGetUserHwidDevicesRes()
}

type InfraBillingCreateInfraBillingHistoryRecordRes interface {
	infraBillingCreateInfraBillingHistoryRecordRes()
}

type InfraBillingCreateInfraBillingNodeRes interface {
	infraBillingCreateInfraBillingNodeRes()
}

type InfraBillingCreateInfraProviderRes interface {
	infraBillingCreateInfraProviderRes()
}

type InfraBillingDeleteInfraBillingHistoryRecordByUuidRes interface {
	infraBillingDeleteInfraBillingHistoryRecordByUuidRes()
}

type InfraBillingDeleteInfraBillingNodeByUuidRes interface {
	infraBillingDeleteInfraBillingNodeByUuidRes()
}

type InfraBillingDeleteInfraProviderByUuidRes interface {
	infraBillingDeleteInfraProviderByUuidRes()
}

type InfraBillingGetBillingNodesRes interface {
	infraBillingGetBillingNodesRes()
}

type InfraBillingGetInfraBillingHistoryRecordsRes interface {
	infraBillingGetInfraBillingHistoryRecordsRes()
}

type InfraBillingGetInfraProviderByUuidRes interface {
	infraBillingGetInfraProviderByUuidRes()
}

type InfraBillingGetInfraProvidersRes interface {
	infraBillingGetInfraProvidersRes()
}

type InfraBillingUpdateInfraBillingNodeRes interface {
	infraBillingUpdateInfraBillingNodeRes()
}

type InfraBillingUpdateInfraProviderRes interface {
	infraBillingUpdateInfraProviderRes()
}

type InternalSquadAddUsersToInternalSquadRes interface {
	internalSquadAddUsersToInternalSquadRes()
}

type InternalSquadCreateInternalSquadRes interface {
	internalSquadCreateInternalSquadRes()
}

type InternalSquadDeleteInternalSquadRes interface {
	internalSquadDeleteInternalSquadRes()
}

type InternalSquadGetInternalSquadAccessibleNodesRes interface {
	internalSquadGetInternalSquadAccessibleNodesRes()
}

type InternalSquadGetInternalSquadByUuidRes interface {
	internalSquadGetInternalSquadByUuidRes()
}

type InternalSquadGetInternalSquadsRes interface {
	internalSquadGetInternalSquadsRes()
}

type InternalSquadRemoveUsersFromInternalSquadRes interface {
	internalSquadRemoveUsersFromInternalSquadRes()
}

type InternalSquadReorderInternalSquadsRes interface {
	internalSquadReorderInternalSquadsRes()
}

type InternalSquadUpdateInternalSquadRes interface {
	internalSquadUpdateInternalSquadRes()
}

type IpControlDropConnectionsRes interface {
	ipControlDropConnectionsRes()
}

type IpControlFetchUserIpsRes interface {
	ipControlFetchUserIpsRes()
}

type IpControlFetchUsersIpsRes interface {
	ipControlFetchUsersIpsRes()
}

type IpControlGetFetchIpsResultRes interface {
	ipControlGetFetchIpsResultRes()
}

type IpControlGetFetchUsersIpsResultRes interface {
	ipControlGetFetchUsersIpsResultRes()
}

type KeygenGenerateKeyRes interface {
	keygenGenerateKeyRes()
}

type MetadataGetNodeMetadataRes interface {
	metadataGetNodeMetadataRes()
}

type MetadataGetUserMetadataRes interface {
	metadataGetUserMetadataRes()
}

type MetadataUpsertNodeMetadataRes interface {
	metadataUpsertNodeMetadataRes()
}

type MetadataUpsertUserMetadataRes interface {
	metadataUpsertUserMetadataRes()
}

type NodePluginCloneNodePluginRes interface {
	nodePluginCloneNodePluginRes()
}

type NodePluginCreateConfigRes interface {
	nodePluginCreateConfigRes()
}

type NodePluginDeleteConfigRes interface {
	nodePluginDeleteConfigRes()
}

type NodePluginGetAllConfigsRes interface {
	nodePluginGetAllConfigsRes()
}

type NodePluginGetConfigByUuidRes interface {
	nodePluginGetConfigByUuidRes()
}

type NodePluginPluginExecutorRes interface {
	nodePluginPluginExecutorRes()
}

type NodePluginReorderNodePluginsRes interface {
	nodePluginReorderNodePluginsRes()
}

type NodePluginUpdateConfigRes interface {
	nodePluginUpdateConfigRes()
}

type NodesBulkNodesActionsRes interface {
	nodesBulkNodesActionsRes()
}

type NodesBulkNodesUpdateRes interface {
	nodesBulkNodesUpdateRes()
}

type NodesCreateNodeRes interface {
	nodesCreateNodeRes()
}

type NodesDeleteNodeRes interface {
	nodesDeleteNodeRes()
}

type NodesDisableNodeRes interface {
	nodesDisableNodeRes()
}

type NodesEnableNodeRes interface {
	nodesEnableNodeRes()
}

type NodesGetAllNodesRes interface {
	nodesGetAllNodesRes()
}

type NodesGetAllNodesTagsRes interface {
	nodesGetAllNodesTagsRes()
}

type NodesGetOneNodeRes interface {
	nodesGetOneNodeRes()
}

type NodesProfileModificationRes interface {
	nodesProfileModificationRes()
}

type NodesReorderNodesRes interface {
	nodesReorderNodesRes()
}

type NodesResetNodeTrafficRes interface {
	nodesResetNodeTrafficRes()
}

type NodesRestartAllNodesRes interface {
	nodesRestartAllNodesRes()
}

type NodesRestartNodeRes interface {
	nodesRestartNodeRes()
}

type NodesUpdateNodeRes interface {
	nodesUpdateNodeRes()
}

type NodesUsageHistoryGetStatsNodesUsageRes interface {
	nodesUsageHistoryGetStatsNodesUsageRes()
}

type PasskeyDeletePasskeyRes interface {
	passkeyDeletePasskeyRes()
}

type PasskeyGetActivePasskeysRes interface {
	passkeyGetActivePasskeysRes()
}

type PasskeyPasskeyRegistrationOptionsRes interface {
	passkeyPasskeyRegistrationOptionsRes()
}

type PasskeyPasskeyRegistrationVerifyRes interface {
	passkeyPasskeyRegistrationVerifyRes()
}

type PasskeyUpdatePasskeyRes interface {
	passkeyUpdatePasskeyRes()
}

type RemnawaveSettingsGetSettingsRes interface {
	remnawaveSettingsGetSettingsRes()
}

type RemnawaveSettingsUpdateSettingsRes interface {
	remnawaveSettingsUpdateSettingsRes()
}

type SnippetsCreateSnippetRes interface {
	snippetsCreateSnippetRes()
}

type SnippetsDeleteSnippetByNameRes interface {
	snippetsDeleteSnippetByNameRes()
}

type SnippetsGetSnippetsRes interface {
	snippetsGetSnippetsRes()
}

type SnippetsUpdateSnippetRes interface {
	snippetsUpdateSnippetRes()
}

type SubscriptionGetSubscriptionInfoByShortUuidRes interface {
	subscriptionGetSubscriptionInfoByShortUuidRes()
}

type SubscriptionPageConfigCloneSubscriptionPageConfigRes interface {
	subscriptionPageConfigCloneSubscriptionPageConfigRes()
}

type SubscriptionPageConfigCreateConfigRes interface {
	subscriptionPageConfigCreateConfigRes()
}

type SubscriptionPageConfigDeleteConfigRes interface {
	subscriptionPageConfigDeleteConfigRes()
}

type SubscriptionPageConfigGetAllConfigsRes interface {
	subscriptionPageConfigGetAllConfigsRes()
}

type SubscriptionPageConfigGetConfigByUuidRes interface {
	subscriptionPageConfigGetConfigByUuidRes()
}

type SubscriptionPageConfigReorderSubscriptionPageConfigsRes interface {
	subscriptionPageConfigReorderSubscriptionPageConfigsRes()
}

type SubscriptionPageConfigUpdateConfigRes interface {
	subscriptionPageConfigUpdateConfigRes()
}

type SubscriptionSettingsGetSettingsRes interface {
	subscriptionSettingsGetSettingsRes()
}

type SubscriptionSettingsUpdateSettingsRes interface {
	subscriptionSettingsUpdateSettingsRes()
}

type SubscriptionTemplateCreateTemplateRes interface {
	subscriptionTemplateCreateTemplateRes()
}

type SubscriptionTemplateDeleteTemplateRes interface {
	subscriptionTemplateDeleteTemplateRes()
}

type SubscriptionTemplateGetAllTemplatesRes interface {
	subscriptionTemplateGetAllTemplatesRes()
}

type SubscriptionTemplateGetTemplateByUuidRes interface {
	subscriptionTemplateGetTemplateByUuidRes()
}

type SubscriptionTemplateReorderSubscriptionTemplatesRes interface {
	subscriptionTemplateReorderSubscriptionTemplatesRes()
}

type SubscriptionTemplateUpdateTemplateRes interface {
	subscriptionTemplateUpdateTemplateRes()
}

type SubscriptionsGetAllSubscriptionsRes interface {
	subscriptionsGetAllSubscriptionsRes()
}

type SubscriptionsGetConnectionKeysByUuidRes interface {
	subscriptionsGetConnectionKeysByUuidRes()
}

type SubscriptionsGetRawSubscriptionByShortUuidRes interface {
	subscriptionsGetRawSubscriptionByShortUuidRes()
}

type SubscriptionsGetSubpageConfigByShortUuidRes interface {
	subscriptionsGetSubpageConfigByShortUuidRes()
}

type SubscriptionsGetSubscriptionByShortUuidProtectedRes interface {
	subscriptionsGetSubscriptionByShortUuidProtectedRes()
}

type SubscriptionsGetSubscriptionByUsernameRes interface {
	subscriptionsGetSubscriptionByUsernameRes()
}

type SubscriptionsGetSubscriptionByUuidRes interface {
	subscriptionsGetSubscriptionByUuidRes()
}

type SystemDebugSrrMatcherRes interface {
	systemDebugSrrMatcherRes()
}

type SystemGetBandwidthStatsRes interface {
	systemGetBandwidthStatsRes()
}

type SystemGetMetadataRes interface {
	systemGetMetadataRes()
}

type SystemGetNodesMetricsRes interface {
	systemGetNodesMetricsRes()
}

type SystemGetNodesStatisticsRes interface {
	systemGetNodesStatisticsRes()
}

type SystemGetRecapRes interface {
	systemGetRecapRes()
}

type SystemGetRemnawaveHealthRes interface {
	systemGetRemnawaveHealthRes()
}

type SystemGetStatsRes interface {
	systemGetStatsRes()
}

type SystemGetX25519KeypairsRes interface {
	systemGetX25519KeypairsRes()
}

type TorrentBlockerReportsGetTorrentBlockerReportsRes interface {
	torrentBlockerReportsGetTorrentBlockerReportsRes()
}

type TorrentBlockerReportsGetTorrentBlockerReportsStatsRes interface {
	torrentBlockerReportsGetTorrentBlockerReportsStatsRes()
}

type TorrentBlockerReportsTruncateTorrentBlockerReportsRes interface {
	torrentBlockerReportsTruncateTorrentBlockerReportsRes()
}

type UserSubscriptionRequestHistoryGetSubscriptionRequestHistoryRes interface {
	userSubscriptionRequestHistoryGetSubscriptionRequestHistoryRes()
}

type UserSubscriptionRequestHistoryGetSubscriptionRequestHistoryStatsRes interface {
	userSubscriptionRequestHistoryGetSubscriptionRequestHistoryStatsRes()
}

type UsersBulkActionsBulkAllExtendExpirationDateRes interface {
	usersBulkActionsBulkAllExtendExpirationDateRes()
}

type UsersBulkActionsBulkAllResetUserTrafficRes interface {
	usersBulkActionsBulkAllResetUserTrafficRes()
}

type UsersBulkActionsBulkDeleteUsersByStatusRes interface {
	usersBulkActionsBulkDeleteUsersByStatusRes()
}

type UsersBulkActionsBulkDeleteUsersRes interface {
	usersBulkActionsBulkDeleteUsersRes()
}

type UsersBulkActionsBulkExtendExpirationDateRes interface {
	usersBulkActionsBulkExtendExpirationDateRes()
}

type UsersBulkActionsBulkResetUserTrafficRes interface {
	usersBulkActionsBulkResetUserTrafficRes()
}

type UsersBulkActionsBulkRevokeUsersSubscriptionRes interface {
	usersBulkActionsBulkRevokeUsersSubscriptionRes()
}

type UsersBulkActionsBulkUpdateAllUsersRes interface {
	usersBulkActionsBulkUpdateAllUsersRes()
}

type UsersBulkActionsBulkUpdateUsersInternalSquadsRes interface {
	usersBulkActionsBulkUpdateUsersInternalSquadsRes()
}

type UsersBulkActionsBulkUpdateUsersRes interface {
	usersBulkActionsBulkUpdateUsersRes()
}

type UsersCreateUserRes interface {
	usersCreateUserRes()
}

type UsersDeleteUserRes interface {
	usersDeleteUserRes()
}

type UsersDisableUserRes interface {
	usersDisableUserRes()
}

type UsersEnableUserRes interface {
	usersEnableUserRes()
}

type UsersGetAllTagsRes interface {
	usersGetAllTagsRes()
}

type UsersGetAllUsersRes interface {
	usersGetAllUsersRes()
}

type UsersGetUserAccessibleNodesRes interface {
	usersGetUserAccessibleNodesRes()
}

type UsersGetUserByIdRes interface {
	usersGetUserByIdRes()
}

type UsersGetUserByShortUuidRes interface {
	usersGetUserByShortUuidRes()
}

type UsersGetUserByTelegramIdRes interface {
	usersGetUserByTelegramIdRes()
}

type UsersGetUserByUsernameRes interface {
	usersGetUserByUsernameRes()
}

type UsersGetUserByUuidRes interface {
	usersGetUserByUuidRes()
}

type UsersGetUserSubscriptionRequestHistoryRes interface {
	usersGetUserSubscriptionRequestHistoryRes()
}

type UsersGetUsersByEmailRes interface {
	usersGetUsersByEmailRes()
}

type UsersGetUsersByTagRes interface {
	usersGetUsersByTagRes()
}

type UsersGetUsersStreamRes interface {
	usersGetUsersStreamRes()
}

type UsersResetUserTrafficRes interface {
	usersResetUserTrafficRes()
}

type UsersResolveUserRes interface {
	usersResolveUserRes()
}

type UsersRevokeUserSubscriptionRes interface {
	usersRevokeUserSubscriptionRes()
}

type UsersUpdateUserRes interface {
	usersUpdateUserRes()
}
