// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/uri"
)

// EncodeURI encodes HwidUserDevicesGetAllUsersFilterModes as URI form.
func (s HwidUserDevicesGetAllUsersFilterModes) EncodeURI(e uri.Encoder) error {
	for k, elem := range s {
		if err := e.EncodeField(k, func(e uri.Encoder) error {

			return e.EncodeValue(conv.StringToString(elem))
		}); err != nil {
			return errors.Wrapf(err, "encode field %q", k)
		}
	}
	return nil
}

// DecodeURI decodes HwidUserDevicesGetAllUsersFilterModes from URI form.
func (s *HwidUserDevicesGetAllUsersFilterModes) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode HwidUserDevicesGetAllUsersFilterModes to nil")
	}
	m := s.init()
	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		var elem string
		if err := func() error {
			val, err := d.DecodeValue()
			if err != nil {
				return err
			}

			c, err := conv.ToString(val)
			if err != nil {
				return err
			}

			elem = c
			return nil
		}(); err != nil {
			return errors.Wrapf(err, "decode field %q", k)
		}
		m[string(k)] = elem
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode HwidUserDevicesGetAllUsersFilterModes")
	}

	return nil
}

// EncodeURI encodes TorrentBlockerReportsGetTorrentBlockerReportsFilterModes as URI form.
func (s TorrentBlockerReportsGetTorrentBlockerReportsFilterModes) EncodeURI(e uri.Encoder) error {
	for k, elem := range s {
		if err := e.EncodeField(k, func(e uri.Encoder) error {

			return e.EncodeValue(conv.StringToString(elem))
		}); err != nil {
			return errors.Wrapf(err, "encode field %q", k)
		}
	}
	return nil
}

// DecodeURI decodes TorrentBlockerReportsGetTorrentBlockerReportsFilterModes from URI form.
func (s *TorrentBlockerReportsGetTorrentBlockerReportsFilterModes) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode TorrentBlockerReportsGetTorrentBlockerReportsFilterModes to nil")
	}
	m := s.init()
	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		var elem string
		if err := func() error {
			val, err := d.DecodeValue()
			if err != nil {
				return err
			}

			c, err := conv.ToString(val)
			if err != nil {
				return err
			}

			elem = c
			return nil
		}(); err != nil {
			return errors.Wrapf(err, "decode field %q", k)
		}
		m[string(k)] = elem
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode TorrentBlockerReportsGetTorrentBlockerReportsFilterModes")
	}

	return nil
}

// EncodeURI encodes UserSubscriptionRequestHistoryGetSubscriptionRequestHistoryFilterModes as URI form.
func (s UserSubscriptionRequestHistoryGetSubscriptionRequestHistoryFilterModes) EncodeURI(e uri.Encoder) error {
	for k, elem := range s {
		if err := e.EncodeField(k, func(e uri.Encoder) error {

			return e.EncodeValue(conv.StringToString(elem))
		}); err != nil {
			return errors.Wrapf(err, "encode field %q", k)
		}
	}
	return nil
}

// DecodeURI decodes UserSubscriptionRequestHistoryGetSubscriptionRequestHistoryFilterModes from URI form.
func (s *UserSubscriptionRequestHistoryGetSubscriptionRequestHistoryFilterModes) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode UserSubscriptionRequestHistoryGetSubscriptionRequestHistoryFilterModes to nil")
	}
	m := s.init()
	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		var elem string
		if err := func() error {
			val, err := d.DecodeValue()
			if err != nil {
				return err
			}

			c, err := conv.ToString(val)
			if err != nil {
				return err
			}

			elem = c
			return nil
		}(); err != nil {
			return errors.Wrapf(err, "decode field %q", k)
		}
		m[string(k)] = elem
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode UserSubscriptionRequestHistoryGetSubscriptionRequestHistoryFilterModes")
	}

	return nil
}

// EncodeURI encodes UsersGetUsersFilterModes as URI form.
func (s UsersGetUsersFilterModes) EncodeURI(e uri.Encoder) error {
	for k, elem := range s {
		if err := e.EncodeField(k, func(e uri.Encoder) error {

			return e.EncodeValue(conv.StringToString(elem))
		}); err != nil {
			return errors.Wrapf(err, "encode field %q", k)
		}
	}
	return nil
}

// DecodeURI decodes UsersGetUsersFilterModes from URI form.
func (s *UsersGetUsersFilterModes) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode UsersGetUsersFilterModes to nil")
	}
	m := s.init()
	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		var elem string
		if err := func() error {
			val, err := d.DecodeValue()
			if err != nil {
				return err
			}

			c, err := conv.ToString(val)
			if err != nil {
				return err
			}

			elem = c
			return nil
		}(); err != nil {
			return errors.Wrapf(err, "decode field %q", k)
		}
		m[string(k)] = elem
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode UsersGetUsersFilterModes")
	}

	return nil
}
